import type {
  ActivityDefinition,
  JobOpportunity,
  Opponent,
  Player,
  PersonnelPackage,
  Relationship,
  RelationshipScene,
  MoneyAction,
  StoryEvent,
} from "./types";

export const makePlayerStats = () => ({
  games: 0,
  snaps: 0,
  passAttempts: 0,
  passCompletions: 0,
  passYards: 0,
  passTD: 0,
  interceptionsThrown: 0,
  rushAttempts: 0,
  rushYards: 0,
  rushTD: 0,
  targets: 0,
  receptions: 0,
  receivingYards: 0,
  receivingTD: 0,
  pancakes: 0,
  sacksAllowed: 0,
  tackles: 0,
  tacklesForLoss: 0,
  sacks: 0,
  interceptions: 0,
  passBreakups: 0,
  forcedFumbles: 0,
  fieldGoalsMade: 0,
  fieldGoalsAttempted: 0,
  extraPointsMade: 0,
  extraPointsAttempted: 0,
  punts: 0,
  puntYards: 0,
});

const player = (
  id: string,
  firstName: string,
  lastName: string,
  position: Player["position"],
  grade: Player["grade"],
  overall: number,
  potential: number,
  depthRank: number,
  archetype: string,
  personality: string,
  ratings: [number, number, number, number, number],
  extras: Partial<Player> = {},
): Player => ({
  id,
  firstName,
  lastName,
  position,
  grade,
  archetype,
  personality,
  overall,
  potential,
  ratings: {
    speed: ratings[0],
    strength: Math.round((ratings[0] + ratings[3]) / 2),
    agility: ratings[0],
    stamina: ratings[3],
    technique: ratings[1],
    awareness: ratings[2],
    toughness: ratings[3],
    discipline: ratings[4],
  },
  evaluationConfidence: grade === 12 ? 78 : grade === 11 ? 62 : 45,
  trust: 54,
  morale: 68,
  fatigue: 12,
  health: 100,
  academics: 78,
  leadership: grade === 12 ? 68 : 46,
  depthRank,
  development: 0,
  stats: makePlayerStats(),
  tags: [],
  weeklyReps: 0,
  weeklyGrade: 0,
  gameSnaps: 0,
  injury: null,
  roleNote: "Competing for a defined role.",
  ...extras,
});

export const INITIAL_ROSTER: Player[] = [
  player(
    "qb1",
    "Noah",
    "Bennett",
    "QB",
    12,
    78,
    82,
    1,
    "rhythm passer",
    "steady",
    [69, 80, 83, 71, 88],
    { leadership: 82, tags: ["captain"] },
  ),
  player(
    "qb2",
    "Ty",
    "Callahan",
    "QB",
    10,
    64,
    91,
    2,
    "off-platform creator",
    "fearless",
    [82, 62, 61, 67, 58],
    { evaluationConfidence: 41 },
  ),
  player(
    "qb3",
    "Owen",
    "Price",
    "QB",
    11,
    67,
    74,
    3,
    "game manager",
    "methodical",
    [63, 70, 74, 69, 84],
  ),
  player(
    "rb1",
    "Darius",
    "King",
    "RB",
    11,
    79,
    86,
    1,
    "one-cut runner",
    "driven",
    [87, 77, 72, 82, 76],
  ),
  player(
    "rb2",
    "Malik",
    "Green",
    "RB",
    10,
    70,
    88,
    2,
    "space player",
    "quiet",
    [91, 64, 63, 67, 73],
  ),
  player(
    "wr1",
    "Jalen",
    "Brooks",
    "WR",
    12,
    81,
    84,
    1,
    "route technician",
    "confident",
    [84, 84, 78, 69, 76],
  ),
  player(
    "wr2",
    "Cole",
    "Harris",
    "WR",
    11,
    74,
    82,
    2,
    "possession target",
    "team-first",
    [72, 78, 76, 78, 85],
  ),
  player(
    "wr3",
    "Micah",
    "Jones",
    "WR",
    10,
    66,
    89,
    3,
    "vertical threat",
    "inconsistent",
    [92, 58, 55, 61, 57],
  ),
  player(
    "ol1",
    "Ben",
    "Russo",
    "OL",
    12,
    77,
    78,
    1,
    "drive blocker",
    "dependable",
    [66, 79, 74, 88, 86],
  ),
  player(
    "ol2",
    "Andre",
    "Mills",
    "OL",
    11,
    72,
    81,
    2,
    "pass protector",
    "analytical",
    [70, 75, 77, 76, 82],
  ),
  player(
    "ol3",
    "Luke",
    "Santos",
    "OL",
    10,
    62,
    84,
    3,
    "raw mauler",
    "emotional",
    [71, 58, 51, 84, 55],
  ),
  player(
    "dl1",
    "Isaiah",
    "Cole",
    "DL",
    12,
    80,
    83,
    1,
    "interior anchor",
    "serious",
    [72, 82, 78, 91, 84],
    { leadership: 79, tags: ["captain"] },
  ),
  player(
    "dl2",
    "Roman",
    "Vega",
    "DL",
    11,
    75,
    84,
    2,
    "edge penetrator",
    "intense",
    [83, 76, 69, 80, 67],
  ),
  player(
    "dl3",
    "Devin",
    "Shaw",
    "DL",
    10,
    66,
    87,
    3,
    "long-frame project",
    "eager",
    [78, 61, 57, 72, 70],
  ),
  player(
    "lb1",
    "Marcus",
    "Bell",
    "LB",
    12,
    73,
    75,
    1,
    "downhill mike",
    "proud leader",
    [72, 76, 70, 88, 68],
    { trust: 74, leadership: 91, tags: ["captain", "locker-room voice"] },
  ),
  player(
    "lb2",
    "Eli",
    "Ward",
    "LB",
    10,
    78,
    95,
    2,
    "instinctive rover",
    "reserved competitor",
    [83, 74, 91, 75, 88],
    {
      evaluationConfidence: 34,
      trust: 47,
      leadership: 48,
      tags: ["hidden ceiling"],
    },
  ),
  player(
    "lb3",
    "Sam",
    "Okafor",
    "LB",
    11,
    71,
    84,
    3,
    "coverage backer",
    "studious",
    [79, 69, 76, 71, 90],
  ),
  player(
    "lb4",
    "Trey",
    "Holloway",
    "LB",
    9,
    58,
    89,
    4,
    "sideline chaser",
    "raw",
    [86, 51, 45, 64, 63],
    { evaluationConfidence: 24 },
  ),
  player(
    "cb1",
    "Jayden",
    "Reed",
    "CB",
    12,
    79,
    81,
    1,
    "press corner",
    "volatile",
    [89, 79, 74, 70, 62],
  ),
  player(
    "cb2",
    "Miles",
    "Foster",
    "CB",
    11,
    75,
    86,
    2,
    "off-man reader",
    "coachable",
    [84, 74, 80, 68, 83],
  ),
  player(
    "cb3",
    "Aaron",
    "Lee",
    "CB",
    10,
    67,
    87,
    3,
    "slot mirror",
    "fun-loving",
    [88, 65, 59, 63, 69],
  ),
  player(
    "s1",
    "Caleb",
    "Stone",
    "S",
    12,
    78,
    80,
    1,
    "box safety",
    "protector",
    [80, 78, 79, 86, 81],
    { leadership: 80 },
  ),
  player(
    "s2",
    "Nico",
    "Grant",
    "S",
    11,
    72,
    88,
    2,
    "center fielder",
    "independent",
    [88, 67, 75, 65, 72],
  ),
  player(
    "s3",
    "Evan",
    "Park",
    "S",
    9,
    57,
    90,
    3,
    "processing project",
    "curious",
    [76, 50, 62, 58, 86],
    { evaluationConfidence: 22 },
  ),
  player(
    "k1",
    "Gabe",
    "Martin",
    "K",
    12,
    70,
    73,
    1,
    "placement specialist",
    "even-keeled",
    [59, 73, 76, 60, 91],
  ),
  player(
    "rb3",
    "Josiah",
    "Brown",
    "RB",
    12,
    68,
    71,
    3,
    "short-yardage back",
    "patient",
    [71, 74, 70, 82, 84],
  ),
  player(
    "rb4",
    "Cam",
    "Douglas",
    "RB",
    9,
    57,
    88,
    4,
    "open-field runner",
    "electric",
    [89, 50, 48, 58, 61],
  ),
  player(
    "wr4",
    "Terrence",
    "Hall",
    "WR",
    12,
    69,
    72,
    4,
    "blocking receiver",
    "selfless",
    [70, 74, 71, 80, 88],
  ),
  player(
    "wr5",
    "Isaac",
    "Young",
    "WR",
    11,
    65,
    80,
    5,
    "slot separator",
    "precise",
    [76, 67, 72, 66, 81],
  ),
  player(
    "wr6",
    "Kendrick",
    "Moss",
    "WR",
    9,
    55,
    91,
    6,
    "raw sprinter",
    "shy",
    [94, 42, 39, 52, 57],
  ),
  player(
    "te1",
    "Mason",
    "Webb",
    "TE",
    12,
    75,
    78,
    1,
    "two-way tight end",
    "reliable",
    [68, 80, 77, 84, 89],
  ),
  player(
    "te2",
    "Jordan",
    "Banks",
    "TE",
    10,
    63,
    86,
    2,
    "move tight end",
    "curious",
    [78, 62, 65, 69, 73],
  ),
  player(
    "te3",
    "Brady",
    "Flores",
    "TE",
    9,
    54,
    84,
    3,
    "long-frame project",
    "earnest",
    [64, 55, 49, 61, 77],
  ),
  player(
    "ol4",
    "Chris",
    "Payne",
    "OL",
    12,
    74,
    76,
    4,
    "steady guard",
    "quiet leader",
    [60, 77, 75, 87, 90],
  ),
  player(
    "ol5",
    "Jamal",
    "Turner",
    "OL",
    11,
    70,
    79,
    5,
    "reach blocker",
    "competitive",
    [72, 72, 69, 77, 76],
  ),
  player(
    "ol6",
    "Riley",
    "Morgan",
    "OL",
    10,
    64,
    82,
    6,
    "center prospect",
    "vocal",
    [62, 67, 66, 75, 85],
  ),
  player(
    "ol7",
    "Kobe",
    "Allen",
    "OL",
    10,
    61,
    85,
    7,
    "power project",
    "hard worker",
    [57, 71, 54, 83, 72],
  ),
  player(
    "ol8",
    "Aiden",
    "Kim",
    "OL",
    9,
    53,
    88,
    8,
    "athletic tackle",
    "analytical",
    [75, 48, 51, 58, 86],
  ),
  player(
    "dl4",
    "Tobias",
    "Price",
    "DL",
    12,
    72,
    74,
    4,
    "base end",
    "disciplined",
    [69, 75, 73, 86, 91],
  ),
  player(
    "dl5",
    "Quincy",
    "Ross",
    "DL",
    11,
    69,
    81,
    5,
    "interior rusher",
    "energetic",
    [74, 71, 64, 75, 68],
  ),
  player(
    "dl6",
    "Logan",
    "White",
    "DL",
    10,
    62,
    84,
    6,
    "nose project",
    "tough",
    [55, 72, 55, 88, 79],
  ),
  player(
    "dl7",
    "Emmett",
    "Scott",
    "DL",
    9,
    55,
    90,
    7,
    "bend rusher",
    "restless",
    [82, 49, 43, 56, 59],
  ),
  player(
    "lb5",
    "Dante",
    "Hill",
    "LB",
    11,
    66,
    80,
    5,
    "special teams ace",
    "fearless",
    [77, 68, 65, 84, 75],
  ),
  player(
    "lb6",
    "Will",
    "Chen",
    "LB",
    9,
    54,
    87,
    6,
    "signal caller project",
    "thoughtful",
    [66, 51, 68, 58, 92],
  ),
  player(
    "cb4",
    "Zion",
    "Carter",
    "CB",
    12,
    71,
    73,
    4,
    "boundary corner",
    "resilient",
    [82, 70, 70, 78, 83],
  ),
  player(
    "cb5",
    "Drew",
    "Evans",
    "CB",
    10,
    63,
    84,
    5,
    "zone corner",
    "patient",
    [79, 61, 71, 62, 86],
  ),
  player(
    "cb6",
    "Kai",
    "Robinson",
    "CB",
    9,
    55,
    89,
    6,
    "press project",
    "bold",
    [88, 48, 44, 57, 55],
  ),
  player(
    "s4",
    "Jace",
    "Murphy",
    "S",
    11,
    68,
    82,
    4,
    "big nickel",
    "physical",
    [72, 72, 69, 84, 72],
  ),
  player(
    "s5",
    "Theo",
    "Nguyen",
    "S",
    10,
    61,
    86,
    5,
    "deep-field learner",
    "careful",
    [82, 54, 63, 60, 88],
  ),
  player(
    "p1",
    "Henry",
    "Lewis",
    "P",
    11,
    68,
    75,
    1,
    "directional punter",
    "calm",
    [57, 66, 73, 64, 93],
  ),
];

const rawOpponents = [
  {
    id: "pine",
    name: "Pine Ridge",
    mascot: "Bears",
    offense: 69,
    defense: 67,
    pace: 48,
    runRate: 64,
    pressureAnswer: 52,
    explosiveRate: 43,
    discipline: 72,
    record: "0-0",
    note: "Heavy outside zone. The quarterback holds the ball against simulated pressure.",
  },
  {
    id: "lake",
    name: "Lake Mercer",
    mascot: "Hawks",
    offense: 73,
    defense: 71,
    pace: 74,
    runRate: 42,
    pressureAnswer: 68,
    explosiveRate: 71,
    discipline: 64,
    record: "1-0",
    note: "Fast tempo and vertical shots from trips. Vulnerable to disguised split-safety looks.",
  },
  {
    id: "bishop",
    name: "Bishop Kane",
    mascot: "Knights",
    offense: 78,
    defense: 77,
    pace: 52,
    runRate: 57,
    pressureAnswer: 82,
    explosiveRate: 67,
    discipline: 86,
    record: "2-0",
    note: "Veteran quarterback identifies pressure. Win with coverage leverage and four-man rush integrity.",
  },
  {
    id: "east",
    name: "East Harbor",
    mascot: "Mariners",
    offense: 66,
    defense: 74,
    pace: 39,
    runRate: 72,
    pressureAnswer: 49,
    explosiveRate: 34,
    discipline: 77,
    record: "1-2",
    note: "Condensed formations, gap runs and play action. Safeties must fit without losing the tight end.",
  },
  {
    id: "royal",
    name: "Royal Palm",
    mascot: "Panthers",
    offense: 81,
    defense: 70,
    pace: 81,
    runRate: 35,
    pressureAnswer: 73,
    explosiveRate: 84,
    discipline: 69,
    record: "4-0",
    note: "Best receiver in the district. Their pace punishes late substitutions and unclear calls.",
  },
  {
    id: "cypress",
    name: "Cypress Bay",
    mascot: "Gators",
    offense: 74,
    defense: 78,
    pace: 58,
    runRate: 61,
    pressureAnswer: 61,
    explosiveRate: 52,
    discipline: 80,
    record: "4-1",
    note: "Balanced offense with a mobile quarterback. Edge discipline matters more than sack hunting.",
  },
  {
    id: "summit",
    name: "Summit Christian",
    mascot: "Eagles",
    offense: 83,
    defense: 82,
    pace: 62,
    runRate: 51,
    pressureAnswer: 79,
    explosiveRate: 76,
    discipline: 91,
    record: "6-0",
    note: "State contender. They punish repeated calls and check at the line based on safety rotation.",
  },
  {
    id: "west",
    name: "Westfield",
    mascot: "Wolves",
    offense: 72,
    defense: 69,
    pace: 66,
    runRate: 48,
    pressureAnswer: 57,
    explosiveRate: 63,
    discipline: 58,
    record: "3-4",
    note: "Talented but penalty-prone. Make them execute long drives instead of gifting explosives.",
  },
  {
    id: "grove",
    name: "Palm Grove",
    mascot: "Rams",
    offense: 77,
    defense: 76,
    pace: 50,
    runRate: 68,
    pressureAnswer: 65,
    explosiveRate: 55,
    discipline: 83,
    record: "6-2",
    note: "Rivalry game. Their senior line leans on defenses; emotion can wreck assignment football.",
  },
  {
    id: "central",
    name: "County Central",
    mascot: "Tigers",
    offense: 80,
    defense: 80,
    pace: 56,
    runRate: 53,
    pressureAnswer: 76,
    explosiveRate: 70,
    discipline: 88,
    record: "7-2",
    note: "Complete roster, few weak links. The fourth quarter will expose fatigue and thin rotations.",
  },
];
export const OPPONENTS: Opponent[] = rawOpponents.map((team, index) => ({
  ...team,
  district: "Atlantic District",
  stateRank: index < 4 ? 8 + index * 7 : null,
  nationalRank: index === 6 ? 94 : null,
  offenseStyle:
    team.runRate > 60
      ? "Run-first multiplicity"
      : team.pace > 70
        ? "Tempo spread"
        : "Balanced play action",
  defenseStyle: team.defense > 77 ? "Pressure match" : "Split-safety zone",
  keyPlayers: [
    "Senior quarterback",
    index % 2 ? "All-district edge" : "Explosive tailback",
  ],
  wins: 0,
  losses: 0,
  pointsFor: 0,
  pointsAgainst: 0,
}));

const relationship = (
  base: Omit<
    Relationship,
    "mood" | "need" | "boundary" | "lastInteraction" | "neglect" | "history"
  >,
  mood: string,
  need: string,
  boundary: string,
): Relationship => ({
  ...base,
  mood,
  need,
  boundary,
  lastInteraction: base.memory,
  neglect: 0,
  history: [
    {
      id: `origin-${base.id}`,
      year: 2026,
      week: 0,
      title: "What connects you",
      detail: base.memory,
      tone: "warm",
      sticky: true,
    },
  ],
});
export const RELATIONSHIPS: Relationship[] = [
  relationship(
    {
      id: "hc",
      name: "Dan Mercer",
      role: "Head coach",
      trust: 68,
      respect: 66,
      closeness: 42,
      status: "Your former position coach",
      memory:
        "He gave you the coordinator title when others thought you were too young.",
    },
    "Supportive, but evaluating you",
    "Honest answers when the plan fails",
    "Do not surprise him publicly",
  ),
  relationship(
    {
      id: "assistant",
      name: "Ray Nolan",
      role: "Defensive backs coach",
      trust: 55,
      respect: 61,
      closeness: 31,
      status: "A capable coworker with his own ambition",
      memory: "He stayed late to help install your first call sheet.",
    },
    "Professionally cautious",
    "Evidence that you listen",
    "Do not take credit for his work",
  ),
  relationship(
    {
      id: "principal",
      name: "Dr. Lena Ortiz",
      role: "Principal",
      trust: 57,
      respect: 54,
      closeness: 24,
      status: "Watching your classroom",
      memory: "She approved your emergency teaching certificate.",
    },
    "Patient, not unlimited",
    "Reliable classroom follow-through",
    "Students cannot become second place",
  ),
  relationship(
    {
      id: "mom",
      name: "Patricia Hayes",
      role: "Mother",
      trust: 88,
      respect: 84,
      closeness: 74,
      status: "Worried you never processed the injury",
      memory: "She drove you home after the surgeon ended your playing career.",
    },
    "Proud and worried",
    "A son who calls without needing something",
    "Do not turn pain into a joke",
  ),
  relationship(
    {
      id: "friend",
      name: "Nate Cole",
      role: "College teammate",
      trust: 75,
      respect: 63,
      closeness: 67,
      status: "Graduate assistant at Coastal State",
      memory:
        "He still introduces you as the best linebacker he played beside.",
    },
    "Loyal, competitive",
    "Permission to talk about the injury honestly",
    "No career favors disguised as friendship",
  ),
  relationship(
    {
      id: "emily",
      name: "Emily Hart",
      role: "School counselor",
      trust: 50,
      respect: 55,
      closeness: 38,
      status: "There may be something here",
      memory: "You talked for an hour after new-teacher orientation.",
    },
    "Interested, observant",
    "Proof you can be present",
    "Do not make every plan tentative",
  ),
];

export const ACTIVITIES: ActivityDefinition[] = [
  {
    id: "film",
    label: "Opponent film",
    short: "Film study",
    description: "Chart formations, protections and third-down tendencies.",
    hours: 4,
    category: "football",
    effects: { scouting: 13, prep: 5, stress: 2, family: -1 },
  },
  {
    id: "install",
    label: "Defensive install",
    short: "LB install",
    description: "Rehearse checks and communication with the defensive unit.",
    hours: 4,
    category: "football",
    effects: { prep: 11, staff: 2, energy: -4 },
  },
  {
    id: "fundamentals",
    label: "Low-contact fundamentals",
    short: "Technique",
    description:
      "Tackling leverage and block destruction without heavy collision load.",
    hours: 3,
    category: "football",
    effects: { prep: 7, energy: -2, staff: 1 },
  },
  {
    id: "contact",
    label: "Live contact period",
    short: "Contact",
    description:
      "Sharper evaluation and toughness at a real fatigue and injury cost.",
    hours: 3,
    category: "football",
    effects: { prep: 12, energy: -8, stress: 3, staff: -1 },
  },
  {
    id: "mentor",
    label: "Mentor Eli Ward",
    short: "Mentor Eli",
    description:
      "Individual film and life conversation with the sophomore linebacker.",
    hours: 2,
    category: "football",
    effects: { prep: 3, staff: 1, energy: -2 },
  },
  {
    id: "grades",
    label: "Grade history papers",
    short: "History grades",
    description: "Stay current in the job that pays your contract.",
    hours: 4,
    category: "teaching",
    effects: { teaching: 12, stress: -2, reputation: 1 },
  },
  {
    id: "family",
    label: "Dinner with Mom",
    short: "Family dinner",
    description: "Be present for the person who carried you through rehab.",
    hours: 3,
    category: "life",
    effects: { family: 10, energy: 4, stress: -6 },
  },
  {
    id: "date",
    label: "Ask Emily to dinner",
    short: "Dinner with Emily",
    description: "Make room for a life that is not measured in wins.",
    hours: 4,
    category: "life",
    effects: { family: 3, energy: 5, stress: -4, cash: -65 },
  },
  {
    id: "rest",
    label: "Go home early",
    short: "Recovery",
    description: "Sleep, ice the old knee and let your mind slow down.",
    hours: 3,
    category: "health",
    effects: { energy: 12, stress: -9 },
  },
  {
    id: "network",
    label: "Call Nate at Coastal State",
    short: "Network",
    description: "Talk ball and keep a college relationship alive.",
    hours: 2,
    category: "career",
    effects: { reputation: 2, stress: 1 },
  },
];

export const EVENTS: StoryEvent[] = [
  {
    id: "depth-chart-meeting",
    eyebrow: "Monday · 7:42 PM · Coaches’ office",
    title: "The depth chart meeting",
    body: "Senior captain Marcus Bell has missed two assignments in three scrimmages. Sophomore Eli Ward sees the field faster—but the locker room still belongs to Marcus. Coach Mercer wants your recommendation before Tuesday’s reps.",
    people: ["Marcus Bell", "Eli Ward", "Dan Mercer"],
    choices: [
      {
        id: "captain",
        title: "Recommend the captain",
        description:
          "Trust experience and protect the room. Give Marcus one more week to clean it up.",
        signals: ["locker room +", "development −", "stability"],
      },
      {
        id: "sophomore",
        title: "Bet on the sophomore",
        description:
          "Tell Mercer that Eli processes the game faster and should take the first series.",
        signals: ["evaluation test", "captain trust −", "ceiling +"],
      },
      {
        id: "split",
        title: "Split the first-team reps",
        description:
          "Delay the choice. Gather more evidence, but divide preparation before opening night.",
        signals: ["information +", "install −", "politics"],
      },
    ],
  },
  {
    id: "papers-or-pressure",
    eyebrow: "Tuesday · 5:18 PM · Empty classroom",
    title: "Two jobs, one deadline",
    body: "Fourteen Reconstruction essays sit ungraded. Coach Mercer just texted that the varsity offense changed its protection package. Tomorrow’s practice is your last clean install day.",
    people: ["Dan Mercer", "Dr. Lena Ortiz"],
    choices: [
      {
        id: "grade",
        title: "Finish every paper",
        description:
          "Protect your classroom reputation. The defensive update can wait until morning.",
        signals: ["teaching +", "prep −", "principal trust +"],
      },
      {
        id: "film",
        title: "Build the pressure menu",
        description:
          "Football gets the night. Accept that the grading backlog will be noticed.",
        signals: ["game plan +", "teaching −", "stress +"],
      },
      {
        id: "honest",
        title: "Tell Mercer you need help",
        description:
          "Ask the defensive assistant to chart protections and own your limits.",
        signals: ["delegation", "staff trust test", "balanced"],
      },
    ],
  },
  {
    id: "parent-pressure",
    eyebrow: "Wednesday · 8:11 PM · Parking lot",
    title: "A father is waiting by your truck",
    body: "Marcus Bell’s father says his son has earned the right to start. He reminds you that his company paid for the new weight-room racks. Nobody else appears to be nearby.",
    people: ["Marcus Bell", "Marcus Bell Sr."],
    choices: [
      {
        id: "boundary",
        title: "Set a hard boundary",
        description:
          "Playing time is decided by the staff. Donations do not enter the room.",
        signals: ["ethics +", "booster tension", "player respect"],
      },
      {
        id: "listen",
        title: "Listen without promising",
        description:
          "Let him speak, take the temperature and document the conversation afterward.",
        signals: ["information +", "political risk", "measured"],
      },
      {
        id: "promise",
        title: "Promise Marcus the start",
        description:
          "Calm the situation tonight and deal with the depth chart later.",
        signals: ["short-term peace", "credibility risk", "memory created"],
      },
    ],
  },
  {
    id: "friday-dinner",
    eyebrow: "Thursday · 9:04 PM · Coaches’ office",
    title: "The invitation you forgot",
    body: "Emily reminds you that you agreed to dinner with her brother Friday after the game. Your third-down plan still has two unanswered empty-formation checks.",
    people: ["Emily Hart"],
    choices: [
      {
        id: "keep",
        title: "Keep your word",
        description:
          "Finish what you can, then show up fully present after the game.",
        signals: ["relationship +", "prep cap", "integrity"],
      },
      {
        id: "cancel",
        title: "Cancel and watch film",
        description:
          "Explain that opening month is different. Football gets every remaining hour.",
        signals: ["prep +", "closeness −", "pattern begins"],
      },
      {
        id: "half",
        title: "Try to do both",
        description:
          "Arrive late, leave early and hope neither side feels cheated.",
        signals: ["stress +", "unreliable risk", "some prep"],
      },
    ],
  },
  {
    id: "injury-question",
    eyebrow: "Friday · 10:36 PM · Stadium gate",
    title: "The reporter asks the right question",
    body: "A local reporter heard Jayden Reed was dizzy after Wednesday’s contact period. The athletic trainer cleared him today, but the reporter wants to know why he took another rep after the first hard collision.",
    people: ["Jayden Reed", "Maya Chen"],
    choices: [
      {
        id: "facts",
        title: "Give the complete timeline",
        description:
          "Explain what you observed, when the trainer intervened and what changes Monday.",
        signals: ["credibility +", "staff exposure", "safety"],
      },
      {
        id: "trainer",
        title: "Refer everything to the trainer",
        description:
          "Say medical decisions are not yours and offer nothing else.",
        signals: ["contained", "cold", "media trust −"],
      },
      {
        id: "deny",
        title: "Say the report is wrong",
        description:
          "Protect the program even though you did see Jayden stumble.",
        signals: ["serious memory", "ethics −", "future exposure"],
      },
    ],
  },
  {
    id: "college-call",
    eyebrow: "Sunday · 4:20 PM · Apartment balcony",
    title: "A door opens sideways",
    body: "Nate says Coastal State needs a low-paid defensive quality-control assistant. It is not an on-field role, but you would be in a Division I building every day. Coach Mercer expects you back next season.",
    people: ["Nate Cole", "Dan Mercer"],
    choices: [
      {
        id: "interest",
        title: "Take the interview",
        description:
          "Learn what the job really is before choosing loyalty or access.",
        signals: ["career option +", "network +", "staff uncertainty"],
      },
      {
        id: "stay",
        title: "Commit to Westhaven",
        description:
          "You need real coordinating reps more than a logo on your résumé.",
        signals: ["authority +", "loyalty +", "D1 access −"],
      },
      {
        id: "leverage",
        title: "Use it for leverage",
        description:
          "Tell Mercer another program wants you and ask for a raise and assistant of your choice.",
        signals: ["salary chance", "trust risk", "ambition"],
      },
    ],
  },
  {
    id: "qb-dinner",
    eyebrow: "Sunday · 5:36 PM · Your apartment",
    title: "The quarterback needs more than film",
    body: "Noah Bennett asks whether he can stop by to study Pine Ridge’s coverage. His mother is working overnight, his grades are slipping and he has been eating most dinners alone. You know mentorship can change a life—and that boundaries matter.",
    people: ["Noah Bennett", "Dan Mercer"],
    choices: [
      {
        id: "staffed",
        title: "Host a staff film dinner",
        description:
          "Invite another coach, include his mother by text and keep the evening structured.",
        signals: ["trust +", "safe boundary", "time −"],
      },
      {
        id: "school",
        title: "Meet at school Monday",
        description:
          "Protect the boundary but delay the help until the building reopens.",
        signals: ["safe", "slower help", "academics"],
      },
      {
        id: "alone",
        title: "Let him come over tonight",
        description:
          "Solve the immediate need privately and tell nobody unless it comes up.",
        signals: ["player trust +", "boundary risk", "private memory"],
      },
    ],
  },
  {
    id: "scheme-dispute",
    eyebrow: "Wednesday · 6:50 PM · Defensive staff room",
    title: "Your assistant challenges you",
    body: "Position coach Ray Nolan says your pressure package is asking the safeties to carry too much. He says it in front of the entire staff—and he has clips queued that support his argument.",
    people: ["Ray Nolan", "Dan Mercer"],
    choices: [
      {
        id: "review",
        title: "Watch every clip together",
        description:
          "Let the best evidence win, even if it changes your plan publicly.",
        signals: ["staff trust +", "adaptability", "ego test"],
      },
      {
        id: "private",
        title: "Move it behind closed doors",
        description:
          "Protect the chain of command, then hear him out one-on-one.",
        signals: ["authority", "staff uncertainty", "measured"],
      },
      {
        id: "shut",
        title: "Shut the challenge down",
        description:
          "The coordinator owns the call sheet. End the meeting and keep the package.",
        signals: ["short-term control", "staff trust −", "blind spot"],
      },
    ],
  },
  {
    id: "alumni-night",
    eyebrow: "Saturday · 12:18 AM · Alumni bar",
    title: "The celebration keeps going",
    body: "Former teammates keep buying rounds after your rivalry win. Your truck is outside, your old knee aches and an assistant offers you his couch. Driving would save an hour tomorrow—but you can feel the drinks.",
    people: ["Nate Cole", "Ray Nolan"],
    choices: [
      {
        id: "ride",
        title: "Leave the truck and get a ride",
        description: "Spend the money, lose the morning and remove the danger.",
        signals: ["cash −", "safety", "reputation protected"],
      },
      {
        id: "couch",
        title: "Take the assistant’s couch",
        description:
          "Accept the inconvenience and face the staff-room jokes Monday.",
        signals: ["staff closeness +", "energy −", "safe"],
      },
      {
        id: "drive",
        title: "Drive yourself home",
        description: "Convince yourself that you are fine and take the risk.",
        signals: ["severe risk", "ethics −", "career threat"],
      },
    ],
  },
  {
    id: "student-crisis",
    eyebrow: "Thursday · 2:47 PM · History classroom",
    title: "One desk stays occupied",
    body: "A sophomore who is not on the football team waits until everyone leaves. His family was evicted yesterday, he has nowhere quiet to study and he asks whether dropping out would make things easier.",
    people: ["Dr. Lena Ortiz", "Emily Hart"],
    choices: [
      {
        id: "team",
        title: "Activate the support team",
        description:
          "Bring in Emily and Ortiz, stay through the handoff and accept losing practice time.",
        signals: ["teaching +", "prep −", "human impact"],
      },
      {
        id: "counselor",
        title: "Walk him to the counselor",
        description:
          "Make a responsible handoff and return to defensive meetings.",
        signals: ["appropriate", "limited connection", "balanced"],
      },
      {
        id: "advice",
        title: "Give advice and leave for practice",
        description:
          "Tell him not to quit and trust that the message is enough.",
        signals: ["prep protected", "teaching risk", "regret"],
      },
    ],
  },
];

export const INITIAL_OPPORTUNITIES: JobOpportunity[] = [
  {
    id: "coastal-qc",
    school: "Coastal State",
    level: "FBS",
    role: "Defensive quality control",
    salary: 32000,
    interest: 18,
    location: "Port Mason, FL",
    why: "Former teammate Nate Cole is on staff.",
    requirements: [
      "A staff advocate",
      "Strong film work",
      "Willingness to take less authority",
    ],
    status: "watching",
  },
  {
    id: "st-anselm-lb",
    school: "St. Anselm College",
    level: "D3",
    role: "Linebackers coach",
    salary: 41000,
    interest: 22,
    location: "Wellsburg, VA",
    why: "The defensive coordinator recruits your county.",
    requirements: [
      "Winning defense",
      "LB development evidence",
      "Coordinator recommendation",
    ],
    status: "watching",
  },
  {
    id: "ridge-hc",
    school: "Ridge Community",
    level: "HS",
    role: "Head coach",
    salary: 59000,
    interest: 12,
    location: "Lake County, FL",
    why: "Administration wants a young culture builder.",
    requirements: ["Leadership 60+", "Winning season", "Clean school record"],
    status: "watching",
  },
];

const starters = (position: Player["position"], count: number) =>
  INITIAL_ROSTER.filter((p) => p.position === position)
    .sort((a, b) => a.depthRank - b.depthRank)
    .slice(0, count);
const slot = (
  label: string,
  allowed: Player["position"][],
  playerId: string,
) => ({ label, allowed, playerId });
export const INITIAL_PACKAGES: PersonnelPackage[] = [
  {
    id: "base",
    name: "Base 4–2–5",
    description: "Your every-down structure with five defensive backs.",
    slots: [
      ...starters("DL", 4).map((p, i) => slot(`DL ${i + 1}`, ["DL"], p.id)),
      ...starters("LB", 2).map((p, i) => slot(`LB ${i + 1}`, ["LB"], p.id)),
      ...starters("CB", 3).map((p, i) => slot(`CB ${i + 1}`, ["CB"], p.id)),
      ...starters("S", 2).map((p, i) => slot(`S ${i + 1}`, ["S"], p.id)),
    ],
  },
  {
    id: "nickel",
    name: "Nickel speed",
    description: "Better coverage and simulated pressure against spread sets.",
    slots: [
      ...starters("DL", 3).map((p, i) =>
        slot(`Rush ${i + 1}`, ["DL", "LB"], p.id),
      ),
      ...starters("LB", 2).map((p, i) =>
        slot(`Backer ${i + 1}`, ["LB", "S"], p.id),
      ),
      ...starters("CB", 4).map((p, i) =>
        slot(`Corner ${i + 1}`, ["CB", "S"], p.id),
      ),
      ...starters("S", 2).map((p, i) =>
        slot(`Safety ${i + 1}`, ["S", "CB"], p.id),
      ),
    ],
  },
  {
    id: "third-down",
    name: "Third-down pressure",
    description: "Your best eleven pass defenders and rushers.",
    slots: [
      ...starters("DL", 3).map((p, i) =>
        slot(`Rusher ${i + 1}`, ["DL", "LB"], p.id),
      ),
      ...starters("LB", 2).map((p, i) =>
        slot(`Blitzer ${i + 1}`, ["LB", "S"], p.id),
      ),
      ...starters("CB", 4).map((p, i) =>
        slot(`Cover ${i + 1}`, ["CB", "S"], p.id),
      ),
      ...starters("S", 2).map((p, i) =>
        slot(`Safety ${i + 1}`, ["S", "CB"], p.id),
      ),
    ],
  },
  {
    id: "goal-line",
    name: "Goal line",
    description: "Heavy bodies and downhill fits inside the five.",
    slots: [
      ...starters("DL", 5).map((p, i) =>
        slot(`Front ${i + 1}`, ["DL", "OL"], p.id),
      ),
      ...starters("LB", 4).map((p, i) =>
        slot(`Fit ${i + 1}`, ["LB", "DL"], p.id),
      ),
      ...starters("S", 2).map((p, i) =>
        slot(`Edge ${i + 1}`, ["S", "LB"], p.id),
      ),
    ],
  },
];

export const RELATIONSHIP_SCENES: RelationshipScene[] = [
  {
    id: "mom-box",
    personId: "mom",
    title: "Mom found the rehab box",
    body: "Patricia calls from the garage. She found your college brace, draft letters and the surgeon’s final report. She asks whether to keep them.",
    trigger: "You have not spoken honestly about the injury in months.",
    choices: [
      {
        id: "visit",
        title: "Drive over and open it together",
        detail: "Make the grief real instead of efficient.",
        hours: 3,
        trust: 6,
        closeness: 10,
        outcome:
          "You sit on the floor with her. Neither of you fixes it, and both of you feel less alone.",
        memoryTitle: "Opened the rehab box together",
        memoryTone: "warm",
      },
      {
        id: "store",
        title: "Ask her to keep it closed",
        detail: "You are not ready tonight.",
        hours: 1,
        trust: 1,
        closeness: -2,
        outcome: "She agrees, but hears how quickly you changed the subject.",
        memoryTitle: "Left the rehab box closed",
        memoryTone: "unresolved",
      },
    ],
  },
  {
    id: "emily-call",
    personId: "emily",
    title: "Emily called",
    body: "She has two tickets to a small history exhibit Friday. She is not asking whether football is busy. She is asking whether you want to go.",
    trigger: "The connection is beginning to require actual choices.",
    choices: [
      {
        id: "go",
        title: "Say yes—and protect the night",
        detail: "Put it on the calendar before film expands.",
        hours: 4,
        cash: 45,
        trust: 7,
        closeness: 9,
        outcome:
          "The date is easy. Emily notices you never check the score app.",
        memoryTitle: "A night that stayed protected",
        memoryTone: "warm",
      },
      {
        id: "raincheck",
        title: "Ask for another night",
        detail:
          "Be honest about the week without promising what you cannot give.",
        hours: 1,
        trust: 2,
        closeness: -1,
        outcome:
          "She accepts the answer but asks you to choose the replacement date now.",
        memoryTitle: "A specific rain check",
        memoryTone: "unresolved",
      },
    ],
  },
  {
    id: "mercer-ambition",
    personId: "hc",
    title: "Mercer closes the office door",
    body: "He heard you took a college call. He asks whether you still want to build this defense or are already planning the exit.",
    trigger: "Your career activity reached your current boss.",
    choices: [
      {
        id: "honest",
        title: "Tell him exactly what the call was",
        detail: "Ambition without secrecy.",
        hours: 2,
        trust: 7,
        closeness: 2,
        respect: 5,
        outcome:
          "He does not love it, but he believes your version because you gave it before he demanded proof.",
        memoryTitle: "Told Mercer the whole truth",
        memoryTone: "proud",
      },
      {
        id: "deflect",
        title: "Call it meaningless networking",
        detail: "Reduce the immediate conflict.",
        hours: 1,
        trust: -6,
        closeness: -2,
        respect: -2,
        outcome:
          "Mercer lets you leave. His next question goes to Nate instead.",
        memoryTitle: "Minimized the college call",
        memoryTone: "tense",
      },
    ],
  },
  {
    id: "ortiz-class",
    personId: "principal",
    title: "Ortiz sits in the back row",
    body: "Your lesson is sharp until a player knocks and asks about practice. The room watches you decide which job owns this hour.",
    trigger: "Your grade backlog and football schedule are visible.",
    choices: [
      {
        id: "class",
        title: "Keep teaching",
        detail: "Tell the player you will see him after the bell.",
        hours: 2,
        trust: 7,
        closeness: 1,
        respect: 6,
        outcome:
          "The student discussion recovers. Ortiz leaves one note: “They knew they mattered.”",
        memoryTitle: "Protected the classroom hour",
        memoryTone: "proud",
      },
      {
        id: "hall",
        title: "Step into the hall",
        detail: "Football interrupts the lesson.",
        hours: 2,
        trust: -7,
        closeness: -1,
        respect: -5,
        outcome:
          "The football problem takes ninety seconds. Regaining the class takes the rest of the period.",
        memoryTitle: "Football entered the classroom",
        memoryTone: "hurt",
      },
    ],
  },
];

export const MONEY_ACTIONS: MoneyAction[] = [
  {
    id: "tutoring",
    label: "History tutoring",
    description: "Two evenings helping local students prepare for exams.",
    hours: 4,
    cash: 180,
    stress: 2,
    fatigue: 3,
    ethics: 1,
    reputation: 1,
    risk: "Low risk, modest income",
  },
  {
    id: "clinic",
    label: "Run a youth clinic",
    description: "A Saturday fundamentals clinic under your name.",
    hours: 6,
    cash: 420,
    stress: 4,
    fatigue: 6,
    ethics: 1,
    reputation: 3,
    risk: "Parents remember the experience",
  },
  {
    id: "officiate",
    label: "Youth league officiating",
    description: "Work three youth games outside your district.",
    hours: 5,
    cash: 260,
    stress: 5,
    fatigue: 5,
    ethics: 0,
    reputation: 0,
    risk: "Stable and exhausting",
  },
  {
    id: "film-job",
    label: "Private film breakdown",
    description: "Create a recruiting cut-up for a family outside Westhaven.",
    hours: 4,
    cash: 350,
    stress: 3,
    fatigue: 3,
    ethics: -1,
    reputation: 2,
    risk: "Conflicts can surface later",
  },
  {
    id: "booster-training",
    label: "Paid booster training",
    description:
      "Train a donor’s son privately while controlling his school depth chart.",
    hours: 3,
    cash: 600,
    stress: 5,
    fatigue: 4,
    ethics: -8,
    reputation: 1,
    risk: "High ethical and exposure risk",
  },
];

EVENTS.push(
  {
    id: "captain-family",
    eyebrow: "Tuesday · 6:05 PM · Equipment room",
    speaker: "Your captain",
    trigger: "A repeated lateness pattern finally has a reason.",
    repeatable: true,
    title: "The captain is late again",
    body: "Your captain admits he has been picking up his little sister while their mother works nights. The team only sees the missed start time.",
    people: ["Team captain", "Dan Mercer"],
    choices: [
      {
        id: "private-plan",
        title: "Build a private transportation plan",
        description: "Hold the standard and solve the real problem.",
        signals: ["trust +", "fairness question", "future callback"],
      },
      {
        id: "bench",
        title: "Bench him publicly",
        description: "Protect one rule for everyone.",
        signals: ["authority", "captain trust −", "locker room reacts"],
      },
      {
        id: "ignore",
        title: "Let it slide",
        description: "Avoid the conflict without addressing the pattern.",
        signals: ["short peace", "credibility risk", "problem remains"],
      },
    ],
  },
  {
    id: "third-string-transfer",
    eyebrow: "Thursday · 4:40 PM · Empty bleachers",
    speaker: "Your third-string quarterback",
    trigger: "He has watched another week of reps go elsewhere.",
    repeatable: true,
    title: "The third-stringer asks what you see",
    body: "He asks if he should transfer. Your evaluation is uncertain: he could become special, or you could be protecting an idea the tape does not support.",
    people: ["Third-string quarterback"],
    choices: [
      {
        id: "invest",
        title: "Give him a real development plan",
        description:
          "Promise measured reps and checkpoints, not a starting job.",
        signals: ["evaluation test", "player trust +", "reps cost"],
      },
      {
        id: "honest",
        title: "Tell him the path is narrow",
        description: "Do not sell hope you cannot defend.",
        signals: ["honesty", "transfer likely", "respect"],
      },
      {
        id: "promise",
        title: "Promise a future start",
        description: "Keep him today with a claim you may regret.",
        signals: ["short trust +", "future callback", "credibility risk"],
      },
    ],
  },
  {
    id: "staff-interview",
    eyebrow: "Friday · 7:12 AM · Coaches’ office",
    speaker: "Ray Nolan",
    trigger: "A rival school requested permission to interview him.",
    repeatable: true,
    title: "Your assistant may join the opponent",
    body: "Nolan tells you before Mercer does. He wants growth and believes your staff sometimes dismisses him.",
    people: ["Ray Nolan", "Dan Mercer"],
    choices: [
      {
        id: "support",
        title: "Support the interview",
        description: "Treat his ambition as legitimate.",
        signals: ["relationship +", "staff risk", "network"],
      },
      {
        id: "counter",
        title: "Fight to expand his role",
        description: "Spend political capital to keep him.",
        signals: ["staff trust +", "Mercer test", "authority shared"],
      },
      {
        id: "block",
        title: "Ask Mercer to block it",
        description: "Protect this season at Nolan’s expense.",
        signals: ["control", "resentment", "future rival"],
      },
    ],
  },
  {
    id: "social-criticism",
    eyebrow: "Sunday · 9:22 PM · Phone screen",
    speaker: "A frustrated player",
    trigger: "His post criticizing the scheme is spreading among students.",
    repeatable: true,
    title: "A player posts about your calls",
    body: "He never names you, but everyone knows who “coaches protecting their favorites” means.",
    people: ["A frustrated player", "Team captain"],
    choices: [
      {
        id: "private",
        title: "Meet privately first",
        description: "Ask what the public post could not say.",
        signals: ["information +", "leadership", "accountability"],
      },
      {
        id: "suspend",
        title: "Suspend him immediately",
        description: "Make public criticism a hard boundary.",
        signals: ["authority", "locker room split", "family meeting"],
      },
      {
        id: "respond",
        title: "Reply online",
        description: "Defend the program in the same public arena.",
        signals: ["escalation", "reporter sees it", "permanent record"],
      },
    ],
  },
);
